### ISSUE TITLE
Missing download sources

### ISSUE THREAD

**Issue by m-kowalska** [Neuroinflab/kCSD-python#126]
https://github.com/Neuroinflab/kCSD-python/blob/2994639fb15d6f5861db673e2ded606c5787d0e1/figures/kCSD_properties/README.txt#L26-L28

https://github.com/Neuroinflab/kCSD-python/blob/2994639fb15d6f5861db673e2ded606c5787d0e1/figures/kCSD_properties/README.txt#L33-L35

https://github.com/Neuroinflab/kCSD-python/blob/2994639fb15d6f5861db673e2ded606c5787d0e1/figures/kCSD_properties/README.txt#L92-L94

**Comment by ccluri** [comment]
Can this be closed now?
