### ISSUE TITLE
Publish to PyPI?

### ISSUE THREAD

**Issue by grahamfindlay** [Neuroinflab/kCSD-python#138]
Any chance that the 2.0 release could be published to PyPI? I have a package `foo` that depends on `kcsd`, but I cannot upload `foo` to PyPI, because PyPI will not accept git URL dependencies. Of course I could fork and publish myself, but I maybe a project author would prefer to? Thanks -Graham

**Comment by m-kowalska** [comment]
Hi Graham, sure, we should do this. We are currently cleaning the code for publication and we would prepare to publish on PyPi a cleaned up version. We realized there are some problems with Binder we would like to fix, and they might affect the code. Is it enough for you if we do this by end of August? Marta & Daniel

**Comment by grahamfindlay** [comment]
Oh sure, no hurry at all! You could also upload it to PyPI as a [pre-release](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#pre-release-versioning), in which case people would install it like `pip install kcsd --pre`. Thanks for having the code available, it's been really useful for some of my projects :)

**Comment by alejoe91** [comment]
Hi guys! Any update on this? @grahamfindlay developed a preprocessor for Neuropixels data based on this repo and we would love to include it into [SpikeInterface](https://github.com/SpikeInterface/spikeinterface) `main`. Relying on a pip-installable version would be great!

**Comment by ccluri** [comment]
Attempting to do this https://github.com/Neuroinflab/kCSD-python/tree/pypiinstall
----
issues with conda (order of installing); must install matplotlib first and it doesn't seem to resolve itself. working on this.

**Comment by ccluri** [comment]
pip install kcsd

now works.
