### ISSUE TITLE
Numpy aliases of builtin types are deprecated, now raise AttributeErrors in several places. 

### ISSUE THREAD

**Issue by grahamfindlay** [Neuroinflab/kCSD-python#141]
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Either numpy requirement should be pinned <1.20.0, or code should be updated to use builtin types (e.g. `complex` rather than `np.complex`).

**Comment by guptadivyansh** [comment]
I updated the code again with the recent changes in upstream kCSD master 
#145 

Please merge before it diverges again.
