### ISSUE TITLE
sKCSD related

### ISSUE THREAD

**Issue by ccluri** [Neuroinflab/kCSD-python#24]
**Pertains to ipynb_tests branch**

1. Whats the difference between kCSD-python/data/ball_and_stick_8 and kCSD/tutorials/Data/ball_and_stick_8 ? All data now moved to kCSD-python/data/* so use this accordingly. [Same for gang_7x7_200] - urgent.

2. Why kCSD-python/kcsd/sKCSD.py and kCSD-python/kcsd/sKCSDCell.py - I am merging these into one single file.

3. kcsd/plotting_functions.py . See if this can me moved / added into the kcsd/validation/ part of the code. Please avoid plotting functions here. @m-kowalska  perhaps you can look into this? 

4. All figures now moved to kCSD-python/figures/sKCSD_paper, tutorials folder reserved for ipython notebooks. If you'd like to write a tutorial that'd be great. Like wise all the figures for the current paper would in this folder. - Also would be useful to generate these said figures and include them here as png - low priority. Add a short readme pointing to the doi of the skcsd paper

5.  kCSD-python/figures/sKCSD/functions.py  - is a poor choice for a file name.

6. pep8 convention is missing. Please fix.

7. In the class definition of sKCSD.py inherits KCSD1D but the documentation reads differently. Which is it? There also seems to be some functions from the original class re-written here - is there some reason for this (for example def forward_model).

8. Remove all sys.path.append for importing kcsd. It is now a package. Use, import kcsd or from kcsd import KCSD1D etc.

More later.
@asiaszmek @danek8317

**Comment by asiaszmek** [comment]
For anaconda numpy.1.8.0 is missing libgfortran, which made the tests fail for conda and conda_min. I have upgraded scipy  to 1.16.1 and numpy to 1.10.4 for both conda and conda_min. 
For now tests pass.

**Comment by ccluri** [comment]
Resolved in PR #27
