### ISSUE TITLE
tutorials in ipynb_tests branch not compatible with Python 3

### ISSUE THREAD

**Issue by m-kowalska** [Neuroinflab/kCSD-python#3]
Files  from ipynb_test branch are not compatible with Python 3:
- widget_helpers.py (dict.keys() return views instead of lists in Python 3)
- tutorial_helpers.py (replace xrange() with range())

**Comment by ccluri** [comment]
I suppose these will be deprecated once we have your class-es based validation code and then Michal can fix these. Thanks!

**Comment by ccluri** [comment]
Can you confirm https://github.com/Neuroinflab/kCSD-python/pull/7 fixed these?
