### ISSUE TITLE
KCSD.py: undefined name 'num_cores' and 'mcmiser'

### ISSUE THREAD

**Issue by m-kowalska** [Neuroinflab/kCSD-python#5]
https://github.com/Neuroinflab/kCSD-python/blob/db7c2eb349d7fea7c5c04416faddbbbf4de661c7/corelib/KCSD.py#L1019

possible solution:
try:
    from skmonaco import mcmiser
    skmonaco_available = True
    import multiprocessing
    num_cores = multiprocessing.cpu_count()
except ImportError:
    skmonaco_available = False

**Comment by ccluri** [comment]
Yup, somehow this got removed in the elephant version because they did not want this dependency.

Send PR, will merge.

https://github.com/Neuroinflab/kCSD-python/blob/44f2104d5be433fbc5a671949a15631e3499221f/KCSD3D.py#L16-L22
