### ISSUE TITLE
y axis label alignment

### ISSUE THREAD

**Issue by ccluri** [Neuroinflab/kCSD-python#63]
https://github.com/Neuroinflab/kCSD-python/blob/7dc8bfea7fde168d55f2d3a9d0063b8aa31de102/figures/kCSD_properties/figure_vectors.py#L191

I think that the magnitudes should be shown as here, as an inset plot - as most of this is otherwise an empty, which does not contain much information. Figure B, previously is now Figure A, inset instead. Open to criticism. 

Can you look into the alignment of the y axis labels, plus the titles compatible with 3.5 python version f'string' doesn't work in 3.5.

Cheers!

**Comment by m-kowalska** [comment]
I am not convinced merging Figure A and B is a good idea. On Figure B we want to show data for more values of M than on figure A.

**Comment by ccluri** [comment]
I understand. My point being, that the plot is showing convergence, does it need more values of M - Do they add new information?

**Comment by ccluri** [comment]
https://github.com/Neuroinflab/kCSD-python/commit/1d1f5c789ac1e92113152550381044ad6bb4f17a

Has the previous version of the figure with the new style corrections
