### ISSUE TITLE
Reliability and error maps.

### ISSUE THREAD

**Issue by ccluri** [Neuroinflab/kCSD-python#75]
All through use 300 dpi resolution

![6x6_broken_electrodes_subplotwith_electrodes](https://user-images.githubusercontent.com/546703/51313254-07f3e200-1a45-11e9-9239-6a55a35f96eb.png)

1) Please upload the scripts to generate these figures
2) Use gridspec and move the cbar to occupy the whole two rows.
3) Use figure_properties and for using consistent font size and font styles.
4) The 'x labels' 'depth' can be omitted for the first row
5) The subplot labels 'A', 'B' etc must be figure labels and not inside the title itself.

Side question - are these same as the error calculation plots in the tutorial? If so we should use consistent cmap.

![reliability_map_random_symm](https://user-images.githubusercontent.com/546703/51313452-7b95ef00-1a45-11e9-8ca4-25a848903dec.png)
1 )The numbers here on the contours are not visible at all - either remove them or use a different color - like blue.
2) The cbar needs units
3) Can you try transparency instead of overlay of two different contours?

![kcsd_with_error_mask](https://user-images.githubusercontent.com/546703/51313561-c9125c00-1a45-11e9-9a7a-cc1ccce9d794.png)
1) Use figure properties for the font size and font consistency
2) D you can reduce the cbar range so that the darks are more visible. You can use colorbar's extend parameter (https://matplotlib.org/gallery/images_contours_and_fields/image_masked.html#sphx-glr-gallery-images-contours-and-fields-image-masked-py)

**Comment by m-kowalska** [comment]
First picture is going to be removed. This is not the standard reliability map but the difference between reliability map for the complete setup and the setup with missing contacts.

@ccluri What do you think about adding the third row to the error calculation plots in the tutorial to show the reliability map for random sources (both small and large) and three plots for calculated differences (5, 10 and 20 missing contacts) in the grey scale?

**Comment by m-kowalska** [comment]
![reliability_map_random_symm](https://user-images.githubusercontent.com/19170212/51316401-d420b880-1a54-11e9-95a1-863567514d8f.png)

@ccluri Does it look better?

**Comment by ccluri** [comment]
@m-kowalska https://www.dropbox.com/sh/6kykj4d3dx3fp5s/AAACtN49VCbAHA9otOfNXbnOa?dl=0
Has the files pre-computed for your convenience and future reference. Download the folders in this into kcsd-python/figures/kCSD_properties folder, and the script from above should work.

**Comment by m-kowalska** [comment]
@ccluri Thank you for providing me with your data :)

In my fork (https://github.com/m-kowalska/kCSD-python/tree/master/figures/kCSD_properties) you can find scripts for figure 6, 7, and 9 with different error calculation (consistent with the formulation from the paper).
