### ISSUE TITLE
utility_functions import kcsd

### ISSUE THREAD

**Issue by mczerwinski** [Neuroinflab/kCSD-python#97]
utility_functions.py imports kcsd
kcsd imports utility_functions

This creates an error when importing uninstalled code, and is a bad practice as far as I am aware.

**Comment by abukaj** [comment]
Move https://github.com/Neuroinflab/kCSD-python/blob/204678556e1878dc52c1e14a0b5662fc05852417/kcsd/utility_functions.py#L42
to the body of `kcsd.utility_functions.load_sim()`?

**Comment by abukaj** [comment]
The issue of circular imports is even deeper: `kcsd.sKCSD1 imports from `kcsd.KCSD` which imports `kcsd.utility_functions` which imports `kcsd` which imports from `kcsd.sKCSD1`.

**Comment by abukaj** [comment]
@asiaszmek, @ccluri is extraction of a new module (`kcsd.sKCSD_utils`) feasible?

**Comment by asiaszmek** [comment]
Yes, I think so. I'll looking at it tomorrow.

**Comment by ccluri** [comment]
I reckon this issue now stands resolved?
